const categories = [
  { id: 'main', name: '主食', icon: '🍚' },
  { id: 'snack', name: '小吃', icon: '🍟' },
  { id: 'drink', name: '饮品', icon: '🥤' },
  { id: 'dessert', name: '甜品', icon: '🍰' },
  { id: 'combo', name: '套餐', icon: '🍱' },
  { id: 'cold', name: '凉菜', icon: '🥒' },
  { id: 'hot', name: '热菜', icon: '🔥' },
]

const colors = [
  'linear-gradient(145deg, #fff3e0, #ffe0b2)',
  'linear-gradient(145deg, #fce4ec, #f8bbd0)',
  'linear-gradient(145deg, #fff8e1, #ffecb3)',
  'linear-gradient(145deg, #e8f5e9, #c8e6c9)',
  'linear-gradient(145deg, #e3f2fd, #bbdefb)',
  'linear-gradient(145deg, #f3e5f5, #e1bee7)',
  'linear-gradient(145deg, #ffebee, #ffcdd2)',
]

const baseFoods = [
  ['main', '招牌牛肉饭', 25, '🍛'],
  ['main', '秘制猪排饭', 22, '🥩'],
  ['main', '老北京炸酱面', 18, '🍜'],
  ['main', '重庆小面', 16, '🍜'],
  ['main', '虾仁蒸饺', 20, '🥟'],
  ['main', '扬州炒饭', 13, '🍚'],
  ['main', '番茄鸡蛋盖饭', 14, '🍅'],
  ['main', '咖喱鸡肉饭', 20, '🍛'],
  ['main', '葱油拌面', 10, '🍝'],
  ['main', '海鲜炒面', 15, '🦐'],
  ['snack', '香酥鸡排', 15, '🍗'],
  ['snack', '黄金薯条', 8, '🍟'],
  ['snack', '章鱼小丸子', 12, '🐙'],
  ['snack', '手抓饼', 10, '🥞'],
  ['snack', '烤肠', 6, '🌭'],
  ['snack', '炸鸡块', 14, '🍗'],
  ['snack', '春卷', 9, '🌯'],
  ['snack', '狼牙土豆', 8, '🥔'],
  ['drink', '珍珠奶茶', 12, '🧋'],
  ['drink', '鲜榨橙汁', 10, '🍊'],
  ['drink', '柠檬蜂蜜水', 8, '🍋'],
  ['drink', '冰镇可乐', 5, '🥤'],
  ['drink', '抹茶拿铁', 15, '🍵'],
  ['drink', '西瓜汁', 9, '🍉'],
  ['dessert', '芒果布丁', 12, '🍮'],
  ['dessert', '提拉米苏', 18, '🍰'],
  ['dessert', '草莓圣代', 14, '🍓'],
  ['dessert', '红豆双皮奶', 10, '🥛'],
  ['dessert', '巧克力慕斯', 16, '🍫'],
  ['combo', '经典双人餐', 48, '🍱'],
  ['combo', '豪华三人餐', 68, '🍱'],
  ['combo', '商务套餐A', 35, '🍽️'],
  ['combo', '商务套餐B', 38, '🍽️'],
  ['combo', '儿童快乐餐', 28, '🧒'],
  ['cold', '凉拌黄瓜', 8, '🥒'],
  ['cold', '口水鸡', 18, '🐔'],
  ['cold', '凉拌木耳', 10, '🍄'],
  ['cold', '皮蛋豆腐', 12, '🥚'],
  ['cold', '凉拌海带丝', 9, '🌿'],
  ['hot', '宫保鸡丁', 22, '🍲'],
  ['hot', '鱼香肉丝', 20, '🥘'],
  ['hot', '麻婆豆腐', 16, '🌶️'],
  ['hot', '糖醋里脊', 24, '🍖'],
  ['hot', '红烧排骨', 28, '🍖'],
  ['hot', '清炒时蔬', 12, '🥬'],
  ['hot', '水煮鱼片', 32, '🐟'],
]

const foods = baseFoods.map(([category, name, price, icon], index) => ({
  id: index + 1,
  category,
  name,
  price,
  icon,
  imageUrl: '',
  bg: colors[index % colors.length],
}))

module.exports = { categories, foods }
